controllerManager:
  namespace: lightrun-k8s-operator
  manager:
    image:
      repository: lightruncom/lightrun-k8s-operator
      tag: latest
      
managerConfig:
  logLevel: 2 # higher number - mor logs
  operatorScope:
    namespaces:
      - default
      - app-ns
    namespacedScope: false
