# permissions for end users to view lightrunjavaagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lightrunjavaagent-viewer-role
rules:
- apiGroups:
  - agents.lightrun.com
  resources:
  - lightrunjavaagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agents.lightrun.com
  resources:
  - lightrunjavaagents/status
  verbs:
  - get
